name: ci

on:
  push:
    branches:
      - "main"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  build:
    permissions:
      contents: write 
    defaults:
      run:
        shell: bash
        working-directory: .
    runs-on: ubuntu-latest
    env:
      GROUP: f3lin
      REPO: queue-master
    steps:
      - uses: actions/checkout@v4

      - name: Unit Tests
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          chmod +x scripts/test.sh
          bash scripts/test.sh

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          chmod +x scripts/git_update_tag.sh
          bash scripts/git_update_tag.sh -v patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.GROUP }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build
        env:
          TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          chmod +x scripts/build.sh
          bash scripts/build.sh

      - name: Push user to Docker Hub
        env:
          TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker push $GROUP/$REPO:$TAG